# ***Assignment : Function***

In [1]:
import sqlite3
import pandas as pd
from IPython.display import display, HTML

# 1. DATABASE SETUP & DATA INSERTION [cite: 92-102]
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Creating the Student_Performance table [cite: 93-102]
cursor.execute("""
CREATE TABLE Student_Performance (
    student_id INT PRIMARY KEY,
    name VARCHAR(50),
    course VARCHAR(30),
    score INT,
    attendance INT,
    mentor VARCHAR(50),
    join_date DATE,
    city VARCHAR(50)
);
""")

# Inserting the Data (Correcting OCR errors from the PDF)
cursor.executescript("""
INSERT INTO Student_Performance VALUES
(101, 'Aarav Mehta', 'Data Science', 88, 92, 'Dr. Sharma', '2023-06-12', 'Mumbai'),
(102, 'Riya Singh', 'Data Science', 76, 85, 'Dr. Sharma', '2023-07-01', 'Delhi'),
(103, 'Kabir Khanna', 'Python', 91, 96, 'Ms. Nair', '2023-06-20', 'Mumbai'),
(104, 'Tanvi Patel', 'SQL', 84, 89, 'Mr. Iyer', '2023-05-30', 'Bengaluru'),
(105, 'Ayesha Khan', 'Python', 67, 81, 'Ms. Nair', '2023-07-18', 'Hyderabad'),
(106, 'Dev Sharma', 'SQL', 73, 78, 'Mr. Iyer', '2023-05-28', 'Pune'),
(107, 'Arjun Verma', 'Tableau', 95, 98, 'Ms. Kapoor', '2023-06-15', 'Delhi'),
(108, 'Meera Pillai', 'Tableau', 82, 87, 'Ms. Kapoor', '2023-06-18', 'Kochi'),
(109, 'Nikhil Rao', 'Data Science', 79, 82, 'Dr. Sharma', '2023-07-05', 'Chennai'),
(110, 'Priya Desai', 'SQL', 92, 94, 'Mr. Iyer', '2023-05-27', 'Bengaluru'),
(111, 'Siddharth Jain', 'Python', 85, 90, 'Ms. Nair', '2023-07-02', 'Mumbai'),
(112, 'Sneha Kulkarni', 'Tableau', 74, 83, 'Ms. Kapoor', '2023-06-10', 'Pune'),
(113, 'Rohan Gupta', 'SQL', 89, 91, 'Mr. Iyer', '2023-05-25', 'Delhi'),
(114, 'Ishita Joshi', 'Data Science', 93, 97, 'Dr. Sharma', '2023-06-25', 'Bengaluru'),
(115, 'Yuvraj Rao', 'Python', 71, 84, 'Ms. Nair', '2023-07-12', 'Hyderabad');
""")

def run_q(title, sql):
    print(f"\n{'='*15} {title} {'='*15}")
    display(pd.read_sql_query(sql, conn))

# ==========================================
# SQL FUNCTIONS ANSWERS [cite: 141-152]
# ==========================================

# Q1: Create a ranking of students based on score (highest first).
run_q("Q1: Student Ranking",
      "SELECT name, score, RANK() OVER(ORDER BY score DESC) as student_rank FROM Student_Performance")

# Q2: Show each student's score and the previous student's score (based on score order).
run_q("Q2: Score with Previous Score",
      "SELECT name, score, LAG(score) OVER(ORDER BY score DESC) as prev_score FROM Student_Performance")

# Q3: Convert names to uppercase and extract month name from join_date.
# (Using SQLite strftime for month extraction)
run_q("Q3: Uppercase and Month",
      """SELECT UPPER(name) as NAME_UPPER,
         CASE strftime('%m', join_date)
            WHEN '05' THEN 'May' WHEN '06' THEN 'June' WHEN '07' THEN 'July'
         END as join_month FROM Student_Performance""")

# Q4: Show each student's name and the next student's attendance (ordered by attendance).
run_q("Q4: Name and Next Attendance",
      "SELECT name, attendance, LEAD(attendance) OVER(ORDER BY attendance) as next_attendance FROM Student_Performance")

# Q5: Assign students into 4 performance groups using NTILE().
run_q("Q5: Performance Groups",
      "SELECT name, score, NTILE(4) OVER(ORDER BY score DESC) as performance_group FROM Student_Performance")

# Q6: For each course, assign a row number based on attendance (highest first).
run_q("Q6: Row Number by Course Attendance",
      "SELECT course, name, attendance, ROW_NUMBER() OVER(PARTITION BY course ORDER BY attendance DESC) as row_num FROM Student_Performance")

# Q7: Calculate enrollment days (from join_date to 2025-01-01).
run_q("Q7: Days Enrolled",
      "SELECT name, join_date, (julianday('2025-01-01') - julianday(join_date)) as days_enrolled FROM Student_Performance")

# Q8: Format join_date as "Month Year".
run_q("Q8: Format Date (Month Year)",
      """SELECT name,
         CASE strftime('%m', join_date)
            WHEN '05' THEN 'May' WHEN '06' THEN 'June' WHEN '07' THEN 'July'
         END || ' ' || strftime('%Y', join_date) as formatted_date FROM Student_Performance""")

# Q9: Replace 'Mumbai' with 'MUM' for display.
run_q("Q9: City Replace",
      "SELECT name, REPLACE(city, 'Mumbai', 'MUM') as city_short FROM Student_Performance")

# Q10: For each course, find the highest score using FIRST_VALUE().
run_q("Q10: Highest Score per Course",
      """SELECT DISTINCT course,
         FIRST_VALUE(score) OVER(PARTITION BY course ORDER BY score DESC) as top_course_score
         FROM Student_Performance""")

=============== Q1: Student Ranking ===============

              name  score  student_rank
0      Arjun Verma     95             1
1     Ishita Joshi     93             2
2      Priya Desai     92             3
3     Kabir Khanna     91             4
4      Rohan Gupta     89             5
5      Aarav Mehta     88             6
6   Siddharth Jain     85             7
7      Tanvi Patel     84             8
8     Meera Pillai     82             9
9       Nikhil Rao     79            10
10      Riya Singh     76            11
11  Sneha Kulkarni     74            12
12      Dev Sharma     73            13
13      Yuvraj Rao     71            14
14     Ayesha Khan     67            15

=============== Q2: Score with Previous Score ===============

              name  score  prev_score
0      Arjun Verma     95         NaN
1     Ishita Joshi     93        95.0
2      Priya Desai     92        93.0
3     Kabir Khanna     91        92.0
4      Rohan Gupta     89        91.0
5      Aarav Mehta     88        89.0
6   Siddharth Jain     85        88.0
7      Tanvi Patel     84        85.0
8     Meera Pillai     82        84.0
9       Nikhil Rao     79        82.0
10      Riya Singh     76        79.0
11  Sneha Kulkarni     74        76.0
12      Dev Sharma     73        74.0
13      Yuvraj Rao     71        73.0
14     Ayesha Khan     67        71.0

=============== Q3: Uppercase and Month ===============

        NAME_UPPER join_month
0      AARAV MEHTA       June
1       RIYA SINGH       July
2     KABIR KHANNA       June
3      TANVI PATEL        May
4      AYESHA KHAN       July
5       DEV SHARMA        May
6      ARJUN VERMA       June
7     MEERA PILLAI       June
8       NIKHIL RAO       July
9      PRIYA DESAI        May
10  SIDDHARTH JAIN       July
11  SNEHA KULKARNI       June
12     ROHAN GUPTA        May
13    ISHITA JOSHI       June
14      YUVRAJ RAO       July

=============== Q4: Name and Next Attendance ===============

              name  attendance  next_attendance
0       Dev Sharma          78             81.0
1      Ayesha Khan          81             82.0
2       Nikhil Rao          82             83.0
3   Sneha Kulkarni          83             84.0
4       Yuvraj Rao          84             85.0
5       Riya Singh          85             87.0
6     Meera Pillai          87             89.0
7      Tanvi Patel          89             90.0
8   Siddharth Jain          90             91.0
9      Rohan Gupta          91             92.0
10     Aarav Mehta          92             94.0
11     Priya Desai          94             96.0
12    Kabir Khanna          96             97.0
13    Ishita Joshi          97             98.0
14     Arjun Verma          98              NaN

=============== Q5: Performance Groups ===============

              name  score  performance_group
0      Arjun Verma     95                  1
1     Ishita Joshi     93                  1
2      Priya Desai     92                  1
3     Kabir Khanna     91                  1
4      Rohan Gupta     89                  2
5      Aarav Mehta     88                  2
6   Siddharth Jain     85                  2
7      Tanvi Patel     84                  2
8     Meera Pillai     82                  3
9       Nikhil Rao     79                  3
10      Riya Singh     76                  3
11  Sneha Kulkarni     74                  3
12      Dev Sharma     73                  4
13      Yuvraj Rao     71                  4
14     Ayesha Khan     67                  4

=============== Q6: Row Number by Course Attendance ===============

          course            name  attendance  row_num
0   Data Science    Ishita Joshi          97        1
1   Data Science     Aarav Mehta          92        2
2   Data Science      Riya Singh          85        3
3   Data Science      Nikhil Rao          82        4
4         Python    Kabir Khanna          96        1
5         Python  Siddharth Jain          90        2
6         Python      Yuvraj Rao          84        3
7         Python     Ayesha Khan          81        4
8            SQL     Priya Desai          94        1
9            SQL     Rohan Gupta          91        2
10           SQL     Tanvi Patel          89        3
11           SQL      Dev Sharma          78        4
12       Tableau     Arjun Verma          98        1
13       Tableau    Meera Pillai          87        2
14       Tableau  Sneha Kulkarni          83        3

=============== Q7: Days Enrolled ===============

              name   join_date  days_enrolled
0      Aarav Mehta  2023-06-12          569.0
1       Riya Singh  2023-07-01          550.0
2     Kabir Khanna  2023-06-20          561.0
3      Tanvi Patel  2023-05-30          582.0
4      Ayesha Khan  2023-07-18          533.0
5       Dev Sharma  2023-05-28          584.0
6      Arjun Verma  2023-06-15          566.0
7     Meera Pillai  2023-06-18          563.0
8       Nikhil Rao  2023-07-05          546.0
9      Priya Desai  2023-05-27          585.0
10  Siddharth Jain  2023-07-02          549.0
11  Sneha Kulkarni  2023-06-10          571.0
12     Rohan Gupta  2023-05-25          587.0
13    Ishita Joshi  2023-06-25          556.0
14      Yuvraj Rao  2023-07-12          539.0

=============== Q8: Format Date (Month Year) ===============

              name formatted_date
0      Aarav Mehta      June 2023
1       Riya Singh      July 2023
2     Kabir Khanna      June 2023
3      Tanvi Patel       May 2023
4      Ayesha Khan      July 2023
5       Dev Sharma       May 2023
6      Arjun Verma      June 2023
7     Meera Pillai      June 2023
8       Nikhil Rao      July 2023
9      Priya Desai       May 2023
10  Siddharth Jain      July 2023
11  Sneha Kulkarni      June 2023
12     Rohan Gupta       May 2023
13    Ishita Joshi      June 2023
14      Yuvraj Rao      July 2023

=============== Q9: City Replace ===============

              name city_short
0      Aarav Mehta        MUM
1       Riya Singh      Delhi
2     Kabir Khanna        MUM
3      Tanvi Patel  Bengaluru
4      Ayesha Khan  Hyderabad
5       Dev Sharma       Pune
6      Arjun Verma      Delhi
7     Meera Pillai      Kochi
8       Nikhil Rao    Chennai
9      Priya Desai  Bengaluru
10  Siddharth Jain        MUM
11  Sneha Kulkarni       Pune
12     Rohan Gupta      Delhi
13    Ishita Joshi  Bengaluru
14      Yuvraj Rao  Hyderabad

=============== Q10: Highest Score per Course ===============

         course  top_course_score
0  Data Science                93
1        Python                91
2           SQL                92
3       Tableau                95